#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
feh --bg-scale images/background.jpg &
polybar -c .config/polybar/garbage.conf &
#picom --config .config/picom/picom.conf &
setxkbmap -option grp:win_space_toggle us,ru &
telegram-desktop &
bspc monitor -d I II III IV V

bspc config border_width         3
bspc config window_gap          12

bspc config top_padding         25
bspc config split_ratio             0.60
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   false
#bspc config focused_border_color   "#32CD32"
bspc config focused_border_color    "#BDD6FF"

# Mice bindings
#   Set mouse 1 to move floating windows
bspc config pointer_action1 move

#   Mouse 2 button resizes the window by side
bspc config pointer_action2 resize_side

#   Mouse 3 button (right mouse) resize by corner
bspc config pointer_action2 resize_corner
bspc rule -a mplayer2 state=floating

# bspc query -T -n focused: tiledRectangle":{"x":1276,"y":48,"width":626,"height":1014}
# bigger window: "x":12,"y":48,"width":1246,"height":1014
bspc rule -a TelegramDesktop desktop='^4' state=floating rectangle=626x1014+1276+48
bspc rule -a Org.gnome.Nautilus desktop='^4' state=floating rectangle=1246x1014+12+48 follow=on

bspc rule -a Chromium desktop='^2'
xsetroot -cursor_name left_ptr &
